name: adaptive_deep_linker
description: A lightweight, highly adaptive deep linking solution for Flutter. Simplifies URL parsing and automated native configuration for Android and iOS.
version: 1.0.0
homepage: https://github.com/oxfaysal/adaptive_deep_linker 
repository: https://github.com/oxfaysal/adaptive_deep_linker
issue_tracker: https://github.com/oxfaysal/adaptive_deep_linker/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 

